[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.tokenizer", "php82Extensions.bcmath", "php82Extensions.ctype", "php82Extensions.curl", "composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan migrate --force && php -S 0.0.0.0:8000 -t public"